config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :projects
  resources :posts
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#home"

  get 'pages/about'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord


	validates :name, :description, :example_link, :email, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord

  # has_one_attached :picture, dependent: :destroy
  # has_many_attached :images, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < InheritedResources::Base
	
def new
	@contact = Contact.new
end

def create
	@contact = Contact.new(contact_params)

	respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, notice: 'Thank you so much for contacting us, we will reach you as soon as possible' }
        format.json { render :new, status: :created, location: :new }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
end



  private

    def contact_params
      params.require(:contact).permit(:name, :description, :example_link, :phone_number, :email)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		
	end

	def about
		
	end
	
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base

  private

    def post_params
      params.require(:post).permit(:title, :subtitle, :description)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base

  private

    def project_params
      params.require(:project).permit(:title, :description, :link, :tech)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/contacts/_form.html.erb
  <div class="container">

    <div class="row" align="center">
      
      <div class="col s12" align="center">
                  <%= form_with(model: contact, local: true) do |form| %>
                    <% if contact.errors.any? %>
                  <div id="error_explanation">
                            <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

                            <ul>
                            <% contact.errors.full_messages.each do |message| %>
                              <li><%= message %></li>
                            <% end %>
                            </ul>
                        
                        <% end %>
                        <div class="form-group" id="contactform">

                              <div class="row" style="margin: 5px;">

                                    <div class="col s4">
                                        <div>
                                          <strong><%= form.label :name %></strong><br>
                                          <%= form.text_field :name, class: 'form-control', style: 'color: white;' %>
                                        </div>
                                    </div>

                                    <div class="col s4">
                                        <div class="field">
                                          <strong><%= form.label :phone_number %></strong><br>
                                          <%= form.text_field :phone_number, class: 'form-control', style: 'color: white;' %>
                                        </div>
                                    </div>

                                  <div class="col s4">
                                      <div class="field">
                                        <strong><%= form.label :email %></strong><br>
                                        <%= form.email_field :email, class: 'form-control', style: 'color: white;' %>
                                      </div>
                                  </div>
                                  
                              </div>

                                <div class="row" style="margin-top: 1%; margin: 5px;">
                                    <div class="field">
                                      <strong><%= form.label :description %></strong><br>
                                      <%= form.text_area :description, :style => 'width: 100%; height: 120px; color: white;', :class => 'form-control' %>
                                    </div> 
                                </div>

                                <div class="row" style="margin-top: 1%; margin: 5px;">
                                    <div class="field">
                                      <strong><%= form.label :example_link %></strong><br>
                                      <%= form.text_field :example_link, :style => 'width: 100%; color: white;', :class => 'form-control' %>
                                    </div>
                                    <p><strong>To better assist you, please send a link you would like to use as an example of your future site, or your current site.</strong></p>
                                </div>

                                <div align="center" class="row" style="margin-top: 3%;">
                                  <%= form.submit "Send", class: "btn waves-effect waves-light", :style => "background-color: #E8D124; color: white; margin-top: 10px; width:23%;" %>
                                </div>
                      </div>

              <% end %>
              </div>

      </div>

    </div>
    
  </div>

app/views/contacts/new.html.erb
<div class="row" align="center" style="margin-top: 15%">
	<h4>Please feel free to reach out!</h4>
	
	<div align="center">
		<div class="row">
	        <ul class="social-network social-circle">
	          <li><a href="https://www.facebook.com/thronetechnology" target="_blank" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
	          <li><a href="https://twitter.com/ThroneTechnolo1" target="_blank" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
	          <li><a href="https://www.instagram.com/thronetechnology/?hl=en" target="_blank" class="icoInstagram" title="Instagram"><i class="fa fa-instagram"></i></a></li>
	          <li><a href="https://www.linkedin.com/in/thronetechnology" target="_blank" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
	        </ul>
	      </div>
	 </div>

	
	<div style="margin-top: 2%">
		<%= render 'form', contact: @contact %>
	</div>
	<div align="center">
		<p>For all inquiries please fill out the form below and we will reach you as soon as possible. Thank you so much for your time!</p>		
	</div>


	




</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Throne Technology</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>
    <link href="https://fonts.googleapis.com/css?family=Assistant&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <style>
        /* width */
        ::-webkit-scrollbar {
            width: 10px;
        }

        /* Track */
        ::-webkit-scrollbar-track {
            box-shadow: inset 0 0 5px lightgrey; 
            border-radius: 10px;
        }
         
        /* Handle */
        ::-webkit-scrollbar-thumb {
            background: darkgrey; 
            border-radius: 10px;
        }

        /* Handle on hover */
        ::-webkit-scrollbar-thumb:hover {
            background: #E8D124; 
        }

         /* Fade in */
          .animate-bottom {
            position: relative;
            -webkit-animation-name: animatebottom;
            -webkit-animation-duration: 1s;
            animation-name: animatebottom;
            animation-duration: 1s
          }

          @-webkit-keyframes animatebottom {
            from { bottom:-100px; opacity:0 } 
            to { bottom:0px; opacity:1 }
          }

          @keyframes animatebottom { 
            from{ bottom:-100px; opacity:0 } 
            to{ bottom:0; opacity:1 }
          }

          #myDiv {
            display: none;
            text-align: center;
          }
      </style>

      <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
  </head>

  <body>

  <header>

        <nav id="nav" style="margin-bottom: 5%"> 

              <div class="nav-wrapper">
                <a href="" class="brand-logo"><img src="https://throneassets.s3.amazonaws.com/tt_bg.png" style="width: 90%; height: auto; margin: 3%;"></a>
                <a href="/" data="no-turbolink" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                <ul class="right hide-on-med-and-down">

                        <li ><%=link_to 'Home', root_path, :style => "text-decoration: none; color: white;" %></li>

                        <li ><%=link_to 'Services', pages_about_path, :style => "text-decoration: none; color: white;" %></li>

                        <li ><%=link_to 'Clients', projects_path, :style => "text-decoration: none; color: white;" %></li>

                        <li ><%=link_to 'Contact', new_contact_path, :style => "text-decoration: none; color: white;" %></li>

                        <li> <a href="https://thronetechnology.podia.com/" target="_blank"> Camp Throne</a> </li>

                </ul>
              </div>
        

              <ul class="sidenav" id="mobile-demo">
                        <li ><%=link_to 'Home', root_path, :style => "text-decoration: none; color: black;" %></li> 

                        <li ><%=link_to 'Services', pages_about_path, :style => "text-decoration: none; color: black;" %></li>

                        <li ><%=link_to 'Clients', projects_path, :style => "text-decoration: none; color: black;" %></li>

                        <li ><%=link_to 'Contact', new_contact_path, :style => "text-decoration: none; color: black;" %></li>

                        <li> <a href="https://thronetechnology.podia.com/" target="_blank"> Camp Throne</a> </li>
              </ul>

        </nav>

   
  </header>
 

 <%= yield %>
 
  <%= render 'partials/footer' %> 
  </body>
</html>

app/views/pages/about.html.erb
<div class="container" style="margin-top: 16%; word-wrap: break-word;" >
		<div class="row" style="margin-top: 15%;" data-aos="fade-up" data-aos-duration="3000">
			<div class="col s4" >
				<div align="center" style="width: 100%; height: 470px; background-color: #E8D124; margin-bottom: 2%; padding: 20px; border-radius: 10px">
					
					<div align="center" style="width: 100%; height: 60%; background-color: white; border-radius: 10px;">
						<%= image_tag asset_path('hand.png'), :rel => 'icon', :type =>  'image/png', :id => 'handLogo' %>
					</div>

					<h3 align="center" style="color: black"><strong>Digital Strategy</strong></h3>
				
					<p style="color: black">Strategic planning for an effective website.</p>

				</div>
				<div style="border-right: solid; border-width: 2px; padding: 10px; margin-bottom: 2%">
					<p>
						<h4><strong>Research</strong></h4>
						The success of any platform is reliant on diligent research and planning. The more we understand your business, your market, and your customer, the better we’ll do at creating a stunning website. 

						<ul>
							<li>Goal Development</li>
							<li>Customer Profiling</li>
							<li>Market Analysis</li>
						</ul>
						
						<h4><strong>Information Architecture</strong></h4>
						Content organization can be a challenging task for any platform. A solid content map will minimize user confusion.

						<ul>
							<li>Site Map Creation</li>
							<li>Naming and Labeling Schemes</li>
							<li>Navigation Practices</li>
							<li>Content Strategy</li>
						</ul>  
						
						<h4><strong>Messaging</strong></h4>
						Good content is born out of thoughtful planning and analysis. A consistent voice will keep your audience interested and engaged. Targeted content will nurture and sustain brand loyalty and excitement.

						<ul>
							<li>Brand Exploration</li>
							<li>Competitive Analysis</li>
							<li>Content Creation</li>
						</ul>

						<h4><strong>User Engagement</strong></h4>
						Utilize the ideal blend of clean, functional design elements and relevant content to make it easy for the right types of visitors to both find and engage with your brand.

						<ul>
							<li>Engaging Content</li>
							<li>Social Media Integration</li>
						</ul>


					</p>
				</div>

			</div>

			<div class="col s4" >
				<div align="center" style="width: 100%; height: 470px; background-color: #E8D124;  margin-bottom: 2%; padding: 20px; border-radius: 10px">

					<div align="center" style="width: 100%; height: 60%; background-color: white; border-radius: 10px;">
						<%= image_tag asset_path('design.png'), :rel => 'icon', :type =>  'image/png', :id => 'designLogo' %>
					</div>

					<h3 align="center" style="color: black"><strong>Web Design</strong></h3>

					<p style="color: black">Beautiful responsive designs, to maximize conversion. </p>
					
				</div>

				<div style="border-right: solid; border-width: 2px; padding: 10px; margin-bottom: 2%">
					<h4><strong>Responsive Design</strong></h4>
				    Over 50 percent of web users search from their phones. If your website lacks a responsive design, it won’t display well on phones. You’ll lose sales and leads when users have to pinch and zoom. With our responsive web design services, you get a polished design so you can maximize conversions.

				    <ul>
				    	<li>Professional Display on any Screen</li>
				    	<li>Target a Wider Audience</li>
				    	<li>Improved Search Rankings</li>
				    </ul>

				    <h4><strong>User Interface</strong></h4>
				    An elegant, intuitive user interface guides your audience throughout your website, making conversion easy. We create streamlined, professional UI solutions that compel users to stay on your site, fill out forms and make purchases.

				    <ul>
				    	<li>Fully Branded Websites</li>
				    	<li>Simple Navigation</li>
				    	<li>Clean, Efficient Designs</li>
				    </ul>

				    <h4><strong>User Experience</strong></h4>
				    If your website is frustrating, users will remember — and may avoid your company as a result. The best websites give the user a pleasurable experience… they’re attractive, easy and satisfying to use. With our professional web design services, we’ll help you create a memorable, positive environment that sets you up for success.

				    <ul>
				    	<li>User-Centered Design</li>
				    	<li>Clear Design Guidelines</li>
				    	<li>Usability Considerations</li>
				    </ul>

				    <h4><strong>User Experience</strong></h4>
				    Custom graphic design work will give your customers a tailored experience and enhance brand recognition. Depending on the usage, templates and stock imagery can dilute your brand by making you indistinguishable from the masses.

				    <ul>
				    	<li>Logos</li>
				    	<li>Branding Materials</li>
				    	<li>Custom Icons</li>
				    	<li>Infographics</li>
				    </ul>				    			    


				</div>

			</div>

			<div class="col s4" >
				<div align="center" style="width: 100%; height: 470px; background-color: #E8D124; margin-bottom: 2%; padding: 20px; border-radius: 10px">

					<div align="center" style="width: 100%; height: 60%; background-color: white; border-radius: 10px;">
						<%= image_tag asset_path('development.png'), :rel => 'icon', :type =>  'image/png', :id => 'developmentLogo'%>
					</div>

					<h4 align="center" style="color: black"><strong>Web Development</strong></h4>

					<p style="color: black">Websites built with usage and scalability at the forefront.</p>
					
				</div>

				<div align="center" style="border-right: solid; border-width: 2px; padding: 10px; margin-bottom: 2%; margin-left: -12% ">
					<ul style="list-style-type: none;">
						<li><%= image_tag asset_path('html5.png'), :rel => 'icon', :type =>  'image/png', :id => 'htmlLogo' %> </li>
						<li><%= image_tag asset_path('css.png'), :rel => 'icon', :type =>  'image/png', :id => 'cssLogo' %> </li>
						<li><%= image_tag asset_path('js.png'), :rel => 'icon', :type =>  'image/png', :id => 'jsLogo' %> </li>
						<li><%= image_tag asset_path('ruby.png'), :rel => 'icon', :type =>  'image/png', :id => 'rubyLogo' %> </li>
						<li><%= image_tag asset_path('Rails.png'), :rel => 'icon', :type =>  'image/png', :id => 'railsLogo' %> </li>
					</ul>
				</div>


			</div>
		</div>

		
</div>

app/views/pages/home.html.erb
	<div class="container">
		
		<div class="row" align="center" style="margin-top: 30%">

			<div class="col s6" align="center" style="margin-top: 5% " data-aos="fade-right" data-aos-duration="1500" data-aos-easing="ease-in-sine">
				<img src="https://throneassets.s3.amazonaws.com/tech_logo_lg.png" style="width: 75%; height: auto">
			</div>

			<div class="col s6" data-aos="fade-left" data-aos-duration="3000" data-aos-easing="ease-in-sine" data-aos-offset="500">
				<div>
						<%= link_to "contact_mail", new_contact_path, class: "large material-icons", style: "color: #E8D124; font-size: 800%;" %> 
						<p style="color: white">Contact</p>
				</div>
				<br>
				
					<div>
						<%= link_to "devices", pages_about_path, class: "large material-icons", style: "color: #E8D124; font-size: 800%;" %>
						<p style="color: white">Services</p>
					</div>
				<br>

				
					<div >
						<%= link_to "people", projects_path, class: "large material-icons", style: "color: #E8D124; font-size: 800%;" %>
						<p style="color: white">Projects</p>
					</div>
			</div>

			
		</div>




		<div class="row" style="margin-top: 25%; margin-bottom: 15%;" align="center" data-aos="fade-up" data-aos-duration="3000">
		<hr>
			<div class="row" style="margin-top: 15%">
				<div class="col s6">
					<img src="https://throneassets.s3.amazonaws.com/camp_flyer(f).png" style="width: 100%; height: auto">
				</div>

				<div class="col s6">
					<img src="https://throneassets.s3.amazonaws.com/camp_flyer(b).png" style="width: 100%; height: auto">
				</div>
			</div>

			<div class="row">
				<a href="https://thronetechnology.podia.com/" class="btn waves-effect waves-light" style="background-color: #E8D124; color: black; margin-top: 10%">Learn More!</a>
			</div>

			
		</div>

		<hr>








		<div class="row" align="center" style="margin-top: 30%; margin-bottom: 35%; word-wrap: break-word;" data-aos="fade-up" data-aos-duration="3000">
			
			

				<div class="col s4">
					
					<div align="center" style="width: 102%; height: 400px; background-color: #E8D124; margin: 2%; padding: 3%; border-radius: 10px">
						
						<div align="center" style="width: 80%; height: 50%; background-color: white; border-radius: 10px;">
							<%= image_tag asset_path('hand.png'), :rel => 'icon', :type =>  'image/png', :id => 'handLogo' %>
						</div>

						<h4 align="center" style="color: black"><strong>Digital Strategy</strong></h4>
					
						<p style="color: black">Strategic planning for an effective website.</p>

					</div>
				</div>

				<div class="col s4">

					<div align="center" style="width: 102%; height: 400px; background-color: #E8D124; margin: 2%; padding: 3%; border-radius: 10px">

						<div align="center" style="width: 80%; height: 50%; background-color: white; border-radius: 10px;">
							<%= image_tag asset_path('design.png'), :rel => 'icon', :type =>  'image/png', :id => 'designLogo' %>
						</div>

						<h4 align="center" style="color: black"><strong>Web Design</strong></h4>

						<p style="color: black">Beautiful responsive designs, to maximize conversion. </p>
						
					</div>
					
				</div>

				<div class="col s4">

					<div align="center" style="width: 102%; height: 400px; background-color: #E8D124; margin: 2%; padding: 3%; border-radius: 10px">

						<div align="center" style="width: 80%; height: 50%; background-color: white; border-radius: 10px;">
							<%= image_tag asset_path('development.png'), :rel => 'icon', :type =>  'image/png', :id => 'developmentLogo'%>
						</div>

						<h4 align="center" style="color: black; width: 100%"><strong>Web Development</strong></h4>

						<p style="color: black">Websites built with usage and scalability at the forefront.</p>
						
					</div>
					
				</div>

				<div class="row">

					<div class="col s12" align="center" style="margin-top:5%;" >
						<%= link_to "adjust", pages_about_path, class: "large material-icons", style: "color: #E8D124; font-size: 500%;" %>
					</div>
					
				</div>
				
			
			
		</div>




		<div class="row" align="center" data-aos="fade-zoom-in" data-aos-duration="3000">
			<div class="col s12">
				<h1 class="quote">FREE WEBSITE AUDIT AND QUOTE</h1>
			</div>
			<div class="col s12">
				<%= image_tag asset_path('group.png'), :rel => 'icon', :type =>  'image/png', :id => 'quoteimg' %>
			</div>
			<div class="col s12">
				<%= link_to "message", new_contact_path, class: "large material-icons", style: "color: #E8D124; font-size: 700%;" %>
			</div>
			
		
		</div>




</div>

app/views/partials/_footer.html.erb
    <!-- Footer -->
    <footer class="footer" style="background-color: #E8D124; height: 40%; width: 100%; padding: 3%; color: black; margin-top: 25%; border-radius: 10px; opacity: 0.8" >

    	<div class="row">
        	<div class="col s6" >
    	    	 <h4 align="center">
    	    		Links:
    	    	</h4>
    			<ul align="center" style="list-style-type: none;">
    				<li><%= link_to "Home", root_path, style: "color: black;" %></li>
    				<li><%=link_to 'News', posts_path, :style => "text-decoration: none; color: black;" %></li>
    				<li><%=link_to 'Projects', projects_path, :style => "text-decoration: none; color: black;" %></li>
    				<li><%= link_to "About Us", pages_about_path, style: "color: black;" %></li>
    				<li><%=link_to 'Contact', new_contact_path, :style => "text-decoration: none; color: black;" %></li>
    				
    			</ul>

    			<br>
    			<br>


    			 
        	</div>

        	<div class="col s6">
        		<h4 align="center">
        			Contact:
        		</h4>

        		<ul align="center" style="list-style-type: none;">
        			<li><strong>Email:</strong> Admin@thronetechnology.com </li>
        			<li><a href="https://www.instagram.com/thronetechnology/?hl=en" target="_blank" class="social-icon"> <i class="fa fa-instagram"></i></a></li>
                    <li><a href="https://twitter.com/ThroneTechnolo1" target="_blank" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="https://www.linkedin.com/in/thronetechnology" target="_blank" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                    <li><a href="https://www.facebook.com/thronetechnology" target="_blank" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
        		</ul>
        	</div>
    	</div>

	

    	<div class="row" align="center">
				<h5>Copyright © 2018</h5>
    	</div>


    </footer>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/index.html.erb
<!-- <p id="notice"><#%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <#% @posts.each do |post| %>
      <tr>
        <td><#%= post.title %></td>
        <td><#%= post.subtitle %></td>
        <td><#%= post.description %></td>
        <td><#%= link_to 'Show', post %></td>
        <td><#%= link_to 'Edit', edit_post_path(post) %></td>
        <td><#%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <#% end %>
  </tbody>
</table>

<br>

<#%= link_to 'New Post', new_post_path %>
 -->

 <div class="row" align="center" style="margin-top: 17%">
   <h1>COMING SOON</h1>
 </div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @post.subtitle %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="field">
    <%= form.label :tech %>
    <%= form.text_area :tech %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/index.html.erb
<!-- <div class="row">
	<div class="col-md-12">
		<div class="col-md-4">
			<div class="image" style="background-color: rgba(255,255,255,0.2); border-radius: 10px; width: 250px; height: 250px">
				<div align="center">
					<a href="https://www.theblackwomanisgodstores.com/" target="_blank"><#%= image_tag asset_path('BLACKWOMANISGOD GOLD.png'), :rel => 'icon', :type =>  'image/png', :id => 'TBWIG', :style => 'width: 275px; height: 100%' %></a>
				</div>
			</div>
		</div>
	</div>
</div>

<#% @projects.each do |project| %>

  <div class="carousel">
  	<#% (0...@project.images.count).each do |image| %>
		<a class="carousel-item"><#%= image_tag(@project.images[image]) %></a>
  	<#% end %>
    
  </div>

<#% end %> -->
<div class="row" data-aos="fade-up" data-aos-duration="2500">
	<div class="carousel" style="height: 1250px" align="center">

		<a class="carousel-item" style="width: 45%; height: 30%" href="https://www.dreamthinkachievecleaning.com/" target="_blank"><img src="https://throneassets.s3.amazonaws.com/Logo-3-4.jpg"><h5 style="color: #E8D124">Dream Think Achieve Cleaning</h5><br>Click to View</a>

	    <a class="carousel-item" style="width: 45%; height: 30%" href="https://www.theblackwomanisgodstores.com/" target="_blank"><img src="https://s3.amazonaws.com/throneassets/tbwig.jpg"><h5 style="color: #E8D124">T.B.W.I.G.S</h5><br>
	    Click to View</a>	

	    <a class="carousel-item" style="width: 45%; height: 30%" href="http://www.exponentialgrowthcapital.com/" target="_blank"><img src="https://throneassets.s3.amazonaws.com/logo.png">
	    <h5 style="color: #E8D124">Exponential Growth Capital</h5><br>Click to View</a>

	      <a class="carousel-item" style="width: 45%; height: 40%"><img src="https://s3.amazonaws.com/throneassets/jiggylogo.png"><h5 style="color: #E8D124">Coming Soon</h5></a>

	    <a class="carousel-item" style="width: 45%; height: 30%" href="https://www.youngpharaoh.net/" target="_blank"><img src="https://throneassets.s3.amazonaws.com/YPL.png"><h5 style="color: #E8D124">Young Pharaoh University</h5><br>Click to View</a>

	    <a class="carousel-item" style="width: 45%; height: 30%"><img src="https://takecareassets.s3.amazonaws.com/takecare_black_background.png"><h5 style="color: #E8D124">Take Care NY <br>Coming Soon</h5></a>

	    




  </div>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Link:</strong>
  <%= @project.link %>
</p>

<p>
  <strong>Tech:</strong>
  <%= @project.tech %>
</p>